[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

[context.production.environment]
  VITE_SUPABASE_URL = "https://kmrdwsgsvfwjdnhrwaxr.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttcmR3c2dzdmZ3amRuaHJ3YXhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1ODYxMTYsImV4cCI6MjA2NTE2MjExNn0.AJteA0C_IApTHyTLwUX7IgD6jf9ARgXF5De-kmYXtZM" 