// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmrdwsgsvfwjdnhrwaxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttcmR3c2dzdmZ3amRuaHJ3YXhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1ODYxMTYsImV4cCI6MjA2NTE2MjExNn0.AJteA0C_IApTHyTLwUX7IgD6jf9ARgXF5De-kmYXtZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);